#define NUM_TEXTURES 29
#define SQUARE_TEXTURE_W 16
#define BOARD_PADDING 32

#define NUM_TEXTURE_H 23
#define NUM_TEXTURE_W 13

#define NUMBER_HEIGHT 46
#define NUMBER_WIDTH 26
#define NUMBER_PADDING 4

#define SMILEY_TEXTURE_W 26
#define BAR_PIXEL_OVERLAP 8

